FROM nginx:alpine

# # ADD . /frontend
# # WORKDIR /frontend

# # COPY . .

# COPY templates /backend/
# COPY . /backend
# WORKDIR /backend

# EXPOSE 8080

COPY . /templates
WORKDIR /templates

COPY . /static
WORKDIR /static

EXPOSE 3000