FROM  --platform=linux/amd64 python:3.8-alpine

# ADD . /frontend
# WORKDIR /frontend

# COPY . .

# COPY templates /backend/
# COPY . /backend
# WORKDIR /backend

# EXPOSE 8080
COPY ./requirements.txt /frontend/requirements.txt
WORKDIR /frontend

RUN pip install -r requirements.txt

COPY ./templates /
WORKDIR /templates

COPY . /static/
WORKDIR /static
# ENTRYPOINT ["python"]

CMD ["python", "-u", "app.py", "--host=0.0.0.0"]
# CMD ["/backend/app.py"]

EXPOSE 3000