version: "3.8"
services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:8080"
    networks:
      - network-frontend
  backend:
    build: ./backend
    # depends_on:
    #   - mongo
    ports:
      - "8888:8888"
    networks:
      - network-frontend
      - network-backend
  # mongo:
  #   image: mongo
  #   restart: always
  #   volumes:
  #     - ./mongodb_data:/data/db
  #   environment: 
  #     MONGODB_INITDB_ROOT_USERNAME: username
  #     MONGODB_INITDB_ROOT_PASSWORD: password
  #   networks:
  #     - network-backend
networks:
  network-backend: 
    driver: bridge
  network-frontend: 
    driver: bridge
  